name: build

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v6
        - uses: denoland/setup-deno@v2
        - name: win-vstudio-debug
          run: |
            ./fibs config win-vstudio-debug
            ./fibs build
        - name: win-vstudio-release
          run: |
            ./fibs config win-vstudio-release
            ./fibs build
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v6
        - uses: denoland/setup-deno@v2
        - name: macos-make-debug
          run: |
            ./fibs config macos-make-debug
            ./fibs build
        - name: macos-make-release
          run: |
            ./fibs config macos-make-release
            ./fibs build
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: denoland/setup-deno@v2
        - name: prepare
          run:  |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
        - name: linux-make-debug
          run: |
            ./fibs config linux-make-debug
            ./fibs build
        - name: linux-make-release
          run: |
            ./fibs config linux-make-release
            ./fibs build
    emscripten:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: denoland/setup-deno@v2
        - name: install emsdk
          run: |
            sudo apt-get install ninja-build
            ./fibs emsdk install
        - name: emsc-ninja-debug
          run: |
            ./fibs config emsc-ninja-debug
            ./fibs build
        - name: emsc-ninja-release
          run: |
            ./fibs config emsc-ninja-release
            ./fibs build
